travis:
  secure:
    BINSTAR_TOKEN: asgyCsmGEJDKee/fAwqsoK/iWX053GE+4kGVHeQPexcT2aQLnfAWhfZ61XOWE/YSj29Oi0ITvthS84JQJI193GRVRf4wkw8LfRahMRiHomMjMahNz9bx8aFxA8dCIvz3gfQmNvT4B8WJw2YN0hVObT3EJp6diaVPN23bZKE1CzBbNDeG0KuBQG7swKsHvPaJiwUX43m3jXbMPrzZnYKMARFzKcRQGNXUKyeOI4VZ336f/m8kV4nDKXwzIdkRn2VdJnKlkAbkcXCiXjIrtUcAOmVEQWjWJqAUNy2NV/3R1VXX8GJ6/EDubcmkBWlZdrchCMsrLoqpPuNtdK4g7u6pS6zvvMjowKPIvRM+iBosgudAqqMJ9UcflV6L5can489TfD9/LQK6pCCb9o2g4aQO8GMlRgiGetknHk3E2CgkD2dfqhou+zH6yjdkUCVq8u8A9fWKk5UOVsS7bTZploHA4FfVWKfkDzEkCStxstaTElo0G9qqAK2fv/4jOByfDtz7VIGfjwL6BG0XzfXu6pcmIxiR+/2ea2mbqTNp2RMc05nCgwb9vKr5tmB77e211rpCA9eXHvWTT6N2iMCi608Fg61mqTsaYjK2YNsAfpy+RThlK5vKVOzLXaXw8R49BNlVLvLmVQZkCL4uBjHgH0fLsp9ejuFC5XUJYcpfw933HaY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
