travis:
  secure:
    BINSTAR_TOKEN: VnvcDaCjueMMuofKIiiy3mxkDkrESk9A2xngk1XcAwoRZ0Xayzvl+LRd26J9Ytuk4P7jK8jA/Ycb5XgU6JEmEKCbtHpJLZn1c2hQ4UxO5GqZjwOWq8xzvKYGkdODbKMOZMWnD7q+XTT/W5S8zuUf+O7r5xbjLPDckNcE7hPE267msDNBBj3KgH9pIw0HPVGH5i7oanVt5UGkv+cfRES0OlOAVqOBij4YQpNcg2APUiPjAcfRESlhY3HzpWnZPKQbnVXHgpRMT0Y1Hd7QWOe3ju7JQtNYZpQDPZzIyA2rXkqiT0w8S/i6G8YFAY75BnPKU1YGNpeZbURSI59f9+doRuAAPVe0G+2IlbxMAbKCa5Ch96xudNulReJneIuoIAGKHKukGiSVovPjMN8quGi/Us9HpJbDQPHtWptLVwn0C8plJmjPjXX99QA4wQgdZC+2l2yUqjkgC+8eQW7lUR+gjKcrUN6lQNk6BFyrFbVlXCToEBTSEvLSr3oMH6W+F6P1h9NEtc8aObprHhP3wMaoP3b1m2Z/iD82yQesfFZh54sY/vZQ/He6+KtBXPtNi9D8FuivOxSuPlP5EsXt0omwVx1uZWgB6/X/PBqKVPs2akTd+qyMQj70qXF4p310l83eUAJGqOibL++gncR7b0P2u5R1hJYjS6NvQJXUqsNViQ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
