travis:
  secure:
    BINSTAR_TOKEN: gaAO6nOGTuOf7qqoSsna5bwSYiQhUXZnFH25u5cnwIICDfXiFu+TEXBcsJPDcOjF0xLSMAhpnuCILQ+EszXIOLyhX63CbwLbE/vKc8R3wxIJ4X397GerLG3FNG0ch8wq9R4XP/KSWQAQ4y7CVpLpL0Q+8LFTfx03+JDGvAYVWY1IoKcwr2hqXNVx/H2ICCufo3mTiEkHz5278aXfR9q7NMEsdmUx1nAuPY48fqwsdXCa0eAbou28EIyk0jSIJVOgexoe3Gh8QQ6/hgd/48OqCMivLGAvJV01B2CyhTMlCYB6Mj/jPofNs5sBWt5YQ73wASn6hw4ZoLpAFgTt6uRrnboJ9HjSQZJveGb5FvjK5BLTB90pGKrh4lP/RVPlKPplUGQnl+aeUjnObrnlUmLPVs05xqmeAWf+xohI4oKVqIJcV+z5+IAZXgnsYyjNmk0eJx67yE4jF97ULYZfw7aqywgXrfG20GMVRZpXn3fzbX8W2+AxGfOXV8M6MNqPGBlgb8vIumLa9ZsCjgBPDFXV+942ixuOm//R96u6+60Do/Y6opMULyPSs1DRzvwga7YD0aBBl8URR9caIZ0+baaozv8HS3mNoJ7QvgmIyZSKtUZAs3KEWRUsJlEH3s82G9a3reQU0BTMt08469yCefSVyLyfgsZ8b0IHVDRtTDZQ1MI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
