travis:
  secure:
    BINSTAR_TOKEN: Zz/HxJOUBFYgDSQaa4PXCJwl6Fukzh14PcOE/O3UfMjNjDhqAuKWOUp0Ea/IjXBr7A5GY0iRh7bwJx04UEVrGj+V5mFVbP/CEsL+I/CPpYj19iS3Ciabl2jR9wPWKJVKDxKg/tmWmopRlZ6ui2Umbb9/2eGHu6BilUOCN9jPWZN+3hQkKw9hXkAjZhLI0Zj81aXTYNVaPMA+VZnWmG9JXI/83YH6ItzQl7YKVcGnyCjwU8DGAuQXQn0zOiiaJTlFwKb9eYNt/XEuRPhNfOZlnyKNprxBAwJJpXlaq4qrSbFIefChTmByGi6+BttW7NpVGxWEgxF/IsKdG1nIyTZ78j6K2HCF7SLtbPN/zjFK153x3Z8ywYxu0Wcw1cp1E24CjWzTts2bLqhodWDL1onJdFsYZr36icK8KYVBjqs4kE8k/RzEQuVmiNms95kQQaKnKZZ0VUuih2+yZ2QvAEU4d1RM9u5bxaEGPIrViM3JXu/kzt6EpfkCQIxVEuo7zVUDq39zNL0RNInbt3li9UAo8uhoRUCPs/aaXGoqxEhTQ2OWcXrXEOjq4YkzYqJj8PFI77VATcsU6PoN2Iuyeou8f2wfP/O7j1cU/tisHb6lA9SYbqg/1k/Nzh+sLv4hLhPLq7OvE7Rn2sZm4zawim/h8iCwsWyBYDwAtEmivCuD4KE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
