travis:
  secure:
    BINSTAR_TOKEN: e5GUl62SB/hDW29tU1UVs/Wp9FyTaahgyLhD/e6KZZbEtzBtpV+02ebjT2OmpTAXr+9lur2SevO9H97eGLua6h+VHAHMLZPmYfxtRVB0srnjLgiYWOKnuJYdtZTigrLg7x3srJ5pc1cEFCA4DRkQJJJ2Na2e9BoEpCmsE4kpK4lWUzk6u5d0cysbkfEKkx7oRBmeFRC/WuEZE6fpFFnk9bpoQAGWPD33Goyq3zH17wrDRhQ/+hHSjZpHLQEnOTQnanEFZyi4SJXDcD1mKGPGxfsNRQLe3ftc0Z1TnZoHe2EvIQ+HI00GtzJNZIgDYQBgyGvD1K8PjMkmjeLHj31K+y1HzZLQP9zqesbYylI8mIEz4miUXrHEvcZyzwS+18xmMnT2Ay1Z2Q6EnP7WQZ4JxrhPLlIGlwapFYE3PRGdKDLGvxG8OeQc++qoDNhp9BFBrj9YilDRVei3IunRvOEv+Xx5GbhsxU28LhATh4fZ1JGplgbsxqO4xh3SaXrLREApXEZlljsNIr6CnMj5QoWcSqW/cXx4nyUSfRXsmbhpsJL1n3We8sDUTYf69BHxAkiRovW8GYEfz6HlhPumvgwrh8TW23f8YfJDjjbyjrdNVyJzOPvRXxoh+8kegSSwDb248J16LsRRTaPI3mtUA83+kec+v0UAJA+yB5fMMNyveBQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
